version: '3'
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    expose:
      - 80
  backend:
    build: ./backend
    env_file:
      - .env
    expose:
      - 80
  reverse:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - ${SERVE_PORT}:80
