version: '3'
services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    env_file:
      - .env
    expose:
      - 3000
  backend:
    build: ./backend
    env_file:
      - .env
    expose:
      - ${BACKEND_PORT}
  reverse:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
